# -*- mode: python ; coding: utf-8 -*-
import os
import sys
import site
import lightning_fabric
import whisperx
import pytorch_lightning
import speechbrain
import blobfile

from PyInstaller.utils.hooks import collect_submodules, collect_data_files, copy_metadata

block_cipher = None

# Which organisation's summary prompts to build in (see prompt_profiles.py):
#   $env:VOXTRANSCRIPT_PROFILE="oblates"; pyinstaller app.spec --clean
# Defaults to "legion". The choice is written to build_profile.py (bundled into the
# app) and build_profile.iss (read by VoxTranscriptSetup.iss for the installer's
# name and version, which comes from version.py).
sys.path.insert(0, SPECPATH)
from prompt_profiles import PROFILES, DEFAULT_PROFILE
from version import __version__
build_profile = os.environ.get('VOXTRANSCRIPT_PROFILE', DEFAULT_PROFILE).strip().lower()
if build_profile not in PROFILES:
    raise SystemExit(f"VOXTRANSCRIPT_PROFILE={build_profile!r} is not one of {sorted(PROFILES)}")
with open(os.path.join(SPECPATH, 'build_profile.py'), 'w', encoding='utf-8') as f:
    f.write(f"# Generated by app.spec. Do not edit or commit.\nPROFILE = {build_profile!r}\n")
with open(os.path.join(SPECPATH, 'build_profile.iss'), 'w', encoding='utf-8') as f:
    f.write(f'; Generated by app.spec. Do not edit or commit.\n#define Profile "{build_profile}"\n#define MyAppVersion "{__version__}"\n')
print(f"*** Building VoxTranscript {__version__} with the '{build_profile}' summary prompts ***")

# Get the path to the speechbrain package
speechbrain_path = os.path.dirname(speechbrain.__file__)

# Collect all submodules of pyannote
pyannote_hidden_imports = collect_submodules('pyannote')

# Collect all data files of pyannote
pyannote_datas = collect_data_files('pyannote')

# Collect all data files of whisperx
whisperx_datas = collect_data_files('whisperx')

# Collect data files for lightning_fabric and pytorch_lightning
lightning_fabric_datas = collect_data_files('lightning_fabric')
pytorch_lightning_datas = collect_data_files('pytorch_lightning')

# Collect all data files and submodules of speechbrain
speechbrain_datas = collect_data_files('speechbrain')
speechbrain_submodules = collect_submodules('speechbrain')

# Get the path to the blobfile package
blobfile_path = os.path.dirname(blobfile.__file__)

# Add ffmpeg to the binaries
ffmpeg_dir = 'ffmpeg'
ffmpeg_files = [(os.path.join(ffmpeg_dir, file), 'ffmpeg') for file in os.listdir(ffmpeg_dir) if file.endswith('.exe')]

a = Analysis(
    ['app.py'],
    # No pathex: PyInstaller already searches the environment it runs from. A
    # hard-coded site-packages here once made builds bundle a stale venv.
    pathex=[],
    binaries=ffmpeg_files,  # Include ffmpeg binaries here
    datas=[
        ('gui', 'gui'),
        ('icons', 'icons'),
        ('pyannote_config.yaml', '.'),
        ('config.py', '.'),
        ('transcriber.py', '.'),
        ('pyannote_diarization.py', '.'),
        ('utils.py', '.'),
        ('models', 'models'),
        (blobfile_path, 'blobfile'),
        (speechbrain_path, 'speechbrain'),
    ] + whisperx_datas + pyannote_datas + lightning_fabric_datas + pytorch_lightning_datas + 
    speechbrain_datas + copy_metadata('speechbrain'),
    hiddenimports=[
        'lightning_fabric',
        'lightning',
        'pytorch_lightning',
        'whisperx',
        'speechbrain',
        'blobfile',
        'build_profile',
    ] + pyannote_hidden_imports + speechbrain_submodules,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['whisper_gui_settings.json'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,  # This ensures --onedir behavior
    name='VoxTranscript',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['icons\\voxtranscript-icon.ico'],
)

# This COLLECT call is what creates the distribution directory
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='VoxTranscript',
)